app/models.py
from flask_login import UserMixin
from . import db

class User(db.Model, UserMixin):
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(30), unique=True)
	password = db.Column(db.String(256), unique=True)
	email = db.Column(db.String(100), unique=True)

	def is_active(self):
		return True

	def __init__(self, username, password, email):
		self.username = username
		self.password = password
		self.email = email

	def generate_password(self, password):
		return generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password, password)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os


db = SQLAlchemy()


def create_app():
	app = Flask(__name__, instance_relative_config=False)
	app.config.from_object("config.DevelopmentConfig")

	db.init_app(app)

	from . import models

	with app.app_context():
		db.create_all()

	login_manager = LoginManager()
	login_manager.login_view = 'views.login'
	login_manager.init_app(app)

	from .models import User

	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(user_id)

	


	from .views import views as views_blueprint
	app.register_blueprint(views_blueprint)


	return app

app/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, current_user, login_required, logout_user
from .models import User
from . import db


views = Blueprint('views', __name__)

@views.route('/')
@login_required
def index():
	return render_template("index.html", username=current_user.username)

@views.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == "POST":
		username = request.form['username']
		password = request.form['password']

		login = User.query.filter_by(username=username).first()

		if not login or not check_password_hash(login.password, password):
			flash("username and password wrong.")
			return redirect(url_for("views.login"))
		
		login_user(login)
		return redirect(url_for("views.index"))
	return render_template("login.html")


@views.route('/register', methods=['GET', 'POST'])
def register():
	if request.method == "POST":
		username = request.form['username']
		password = generate_password_hash(request.form['password'], method='sha256')
		email = request.form['email']

		user = User.query.filter_by(username=username).first()

		if user:
			flash("Email is already exist? ")
			return redirect(url_for("views.register"))

		register = User(username=username, password=password, email=email)

		db.session.add(register)

		db.session.commit()

		return redirect(url_for("views.login"))

	return render_template('register.html')


@views.route("/logout")
def logout():
	logout_user()
	return render_template("index.html")

app/templates/includes/header.html
<head>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<header class="nav-bar">
	<ul class="nav-item">
		<li><a href="{{ url_for('views.index') }}">Home</a></li>
		{% if not current_user.is_authenticated %}
		<li><a href="{{ url_for('views.login') }}">Login</a></li>
		<li><a href="{{ url_for('views.register') }}">Register</a></li>
		{% endif %}
		{% if current_user.is_authenticated %}
		<li><a href="{{ url_for('views.logout') }}">Logout</a></li>
		{% endif %}
		<li><a href="#">About</a></li>
	</ul>
</header>

app/templates/index.html
{% extends "layout.html" %}

{% block title %}Home page{% endblock %}


{% block main %}
<div class="container">
	<h1>welcome to flask login app</h1>
</div>
<div class="user">
	{% if current_user.is_authenticated %}
	<h3>Hi, {{ current_user.username }}</h3>
	{% endif %}
</div>
{% if not current_user.is_authenticated %}
<div class="login_func">
	<h3>Let's Started</h3>
	<p>If already Register? <a href="{{ url_for('views.login') }}">Login</a></p>
	{% endif %}
</div>


{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	{% include "includes/header.html" %}

	{% block main %}
		
	{% endblock %}

	{% include "includes/footer.html" %}
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block main %}

<div class="login-container">
	{% with messages = get_flashed_messages() %}
	{% if messages %}
		<div class="alert-box">
			{{ messages }}
		</div>
	{% endif %}
	{% endwith %}
	<form name="login" action="/login" method="POST">
		<h3>Login</h3>
		<hr>
		<label for="username">Username:</label>
		<input type="text" name="username" placeholder="Enter your username" required>
		<label for="password">Password:</label>
		<input type="password" name="password" placeholder="Enter your password" required>
		<button class="btn" type="submit" value="submit">Login</button>
	</form>
</div>


{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock %}

{% block main %}

<div class="login-container">
	<form name="register" action="/register" method="POST">
		{% with messages = get_flashed_messages() %}
		{% if messages %}
		<div class="alert-box">
			{{ messages[0] }}<a href="{{ url_for('views.login') }}">Login</a>
		</div>
		{% endif %}
		{% endwith %}
		<h3>new user</h3>
		<hr>
		<label for="username">Username:</label>
		<input type="text" name="username" id="username" placeholder="Enter your username" required>
		<br>
		<label for="password">Password:</label>
		<input type="password" name="password" id="password" placeholder="Enter your password" required>
		<label for="password">Email:</label>
		<input type="email" name="email" id="email" placeholder="Enter your email" required>
		<button class="btn" type="submit" value="submit">register</button>
	</form>
</div>


{% endblock %}